CreativeNotes\Domain\Entity\User:
  type: entity
  repositoryClass: CreativeNotes\Infrastructure\Repository\NoteRepository
  table: note
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
    content:
      type: text
    createDate:
      type: datetime
      column: create_date